version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - travel-planner-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=travel_planner
      - DB_USERNAME=${DB_USERNAME:-travel_user}
      - DB_PASSWORD=${DB_PASSWORD:-travel_password}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # API密钥通过环境变量传入
      - AMAP_API_KEY=${AMAP_API_KEY}
      - XUNFEI_APP_ID=${XUNFEI_APP_ID}
      - XUNFEI_API_SECRET=${XUNFEI_API_SECRET}
      - XUNFEI_API_KEY=${XUNFEI_API_KEY}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-qwen-plus}
      - ALIBABA_CLOUD_ACCESS_KEY_ID=${ALIBABA_CLOUD_ACCESS_KEY_ID}
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    depends_on:
      - database
      - redis
    networks:
      - travel-planner-network
    volumes:
      - ./backend/logs:/app/logs

  # 数据库服务
  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=travel_planner
      - MYSQL_USER=${DB_USERNAME:-travel_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-travel_password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-travel_password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - travel-planner-network

  # Redis缓存服务
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - travel-planner-network
    command: redis-server --appendonly yes

  # Nginx反向代理 (生产环境)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - travel-planner-network
    profiles:
      - production

volumes:
  mysql_data:
  redis_data:

networks:
  travel-planner-network:
    driver: bridge